# Generated by Django 4.2.7 on 2023-12-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authmodules', '0003_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
