# Generated by Django 4.2.7 on 2023-12-10 14:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('Price', models.FloatField(default=0)),
                ('Date_posted', models.DateField(auto_now_add=True)),
                ('Views', models.IntegerField(default=0)),
                ('Rating', models.FloatField(default=0)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendors')),
            ],
        ),
    ]
