# Generated by Django 4.2.7 on 2023-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='x',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
