# Generated by Django 4.2.7 on 2023-12-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
